apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: mern-backend
          image: aravind2003/ci-cd-fs:latest   # Jenkins will replace tag
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
